# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim

# RUN apt-get clean \
#     && apt-get -y update \
#     && apt-get -y install build-essential \
#     && apt-get -y install procps \
#     && apt-get -y install libpq-dev

# WORKDIR /app

# COPY requirements.txt /app/requirements.txt
# RUN pip install --upgrade pip \
#     && pip install --no-cache-dir --upgrade -r /app/requirements.txt

# ENV TZ Asia/Seoul

# COPY ./src /app

# FROM python:3.9

# WORKDIR /code

# COPY ./requirements.txt /code/requirements.txt

# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# COPY ./app /code/app

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]